name: Leave Comment on PR
on: pull_request
inputs:
  pr_id:
    description: 'Pull request ID'
    required: true
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        id: comment-pr
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ inputs.pr_id }}
          body: "comment PR."
