name: Leave Comment on PR
on: pull_request
jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment to PR
        uses: actions/github-script@v6  # Action to interact with the PR
        with:
          script: "Action finished!"  # Comment text
